<?php

/**
 * Implements hook_query_alter
 */
function sbir_search_query_alter(&$query) {
  //dpm($query);
  // This is a search result query and we want to change the
  // number of search results per page to 16.
  if ($query instanceof PagerDefault && ($tables = $query->getTables()) && isset($tables['i']['table']) && $tables['i']['table'] === 'search_index') {
    $query->limit(20);
  }
    $is_search = FALSE;
  foreach ($query->getTables() as $table) {
    if ($table['table'] == 'search_index') {
      $is_search = TRUE;
    }
  }

  if ($is_search) {
    $query->condition('n.type', 'sbir_announcement', '<>');
    
    $query->condition('n.type', 'sbir_block', '<>');
    $query->condition('n.type', 'sbir_subscription', '<>');
    $query->condition('n.title', '%Home Page', 'NOT LIKE');
  }
}

/**
 * Implements hook_form_alter
 */
function sbir_search_form_alter(&$form, &$form_state, $form_id) {

  if (in_array($form_id, array('search_block_form'))) {

    // Adding placeholders to fields
    $form['search_block_form']['#attributes']['placeholder'] = t('Search...');
  }
}

/**
 * Implements hook_search_page
 */
/*
function sbir_search_search_page($results) {
  print "made it here";exit;
  $output['prefix']['#markup'] = '<ol class="search-results">';

  foreach ($results as $entry) {
    $output[] = array(
      '#theme' => 'search_result',
      '#result' => $entry,
      '#module' => 'sbir_search',
    );
  }
  $output['suffix']['#markup'] = '</ol>' . theme('pager');

  return $output;
}
 */