<?php

/**
 * Implements hook_date_formats().
 */
function sbir_settings_date_formats() {
  return array(
    // Creates a new format for a new, custom format type for the SBIR site.
    array(
      //'title' => 'SBIR Standard',
      'type' => 'sbir_standard',
      'format' => 'F j, Y',
      'locales' => array(),
    ),
    array(
      //'title' => 'SBIR Standard',
      'type' => 'sbir_standard_long',
      'format' => 'F j, Y g:i A',
      'locales' => array(),
    )
  );
}

/**
 * Implements hook_date_format_types().
 */
function sbir_settings_date_format_types() {
  return array(
    'sbir_standard' => t('SBIR Standard'),
    'sbir_standard_long' => t('SBIR Standard Long'),
  );
}

// Configure content types to use workflow revisions
function _sbir_settings_setup_workflow_settings() {
  variable_set('node_options_sbir_announcement', array('0' => 'moderation', '1', 'revision'));
  variable_set('node_options_sbir_basic_page', array('0' => 'moderation', '1', 'revision'));
  variable_set('node_options_sbir_block', array('0' => 'moderation', '1', 'revision'));
  variable_set('node_options_sbir_event', array('0' => 'moderation', '1', 'revision'));
  variable_set('node_options_sbir_file', array('0' => 'moderation', '1', 'revision'));
  variable_set('node_options_sbir_success_story', array('0' => 'moderation', '1', 'revision'));

  variable_set('workbench_moderation_default_state_sbir_announcement', 'draft');
  variable_set('workbench_moderation_default_state_sbir_basic_page', 'draft');
  variable_set('workbench_moderation_default_state_sbir_block', 'draft');
  variable_set('workbench_moderation_default_state_sbir_event', 'draft');
  variable_set('workbench_moderation_default_state_sbir_file', 'draft');
  variable_set('workbench_moderation_default_state_sbir_success_story', 'draft');
}