<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function sbir_global_template_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/*
 * Create the footer menus for the site.
 */

function sbir_global_template_create_footer_menu() {

  $menu = array(
    'menu_name' => 'menu-footer-menu',
    'title' => 'Footer Menu',
    'description' => 'All menu items that appear in the footer of the SBIR site',
  );

  menu_save($menu);

  $plid = 0;
  $menu_name = "menu-footer-menu";
  $weight = 0;

  $title = 'Home';
  $path = '<front>';
  sbir_base_create_menu_link($menu_name, $title, 1, $path, $plid, 0);

  $title = 'Contact Us';
  $alias = "about/contactus";
  $path = drupal_lookup_path("source", $alias);
  $parts = explode('/', $path);
  $nid = $parts[1];
  sbir_base_create_menu_link($menu_name, $title, 2, 'node/' . $nid, $plid, 0);

  $title = 'Policies';
  $alias = 'policies';
  $nid = sbir_basic_pages_create_basic_page($title, $alias);
  sbir_base_create_menu_link($menu_name, $title, 3, 'node/' . $nid, $plid, 0);

  $title = 'Accessibility';
  $path = 'http://sbir.cancer.gov/accessibility.asp';
  sbir_base_create_menu_link($menu_name, $title, 4, $path, $plid, 1);

  $title = 'Viewing Files';
  $path = 'http://www.cancer.gov/global/viewing-files';
  sbir_base_create_menu_link($menu_name, $title, 5, $path, $plid, 1);

  $title = 'Site Map';
  $alias = 'sitemap';
  $nid = sbir_basic_pages_create_basic_page($title, $alias);
  sbir_base_create_menu_link($menu_name, $title, 6, 'node/' . $nid, $plid, 0);

  $title = 'U.S. Department of Health and Human Services';
  $path = 'http://www.hhs.gov';
  sbir_base_create_menu_link($menu_name, $title, 7, $path, $plid, 1);

  $title = 'National Institutes of Health';
  $path = 'http://www.nih.gov';
  sbir_base_create_menu_link($menu_name, $title, 8, $path, $plid, 1);

  $title = 'National Cancer Institute';
  $path = 'http://www.cancer.gov';
  sbir_base_create_menu_link($menu_name, $title, 9, $path, $plid, 1);

  $title = 'USA.gov';
  $path = 'http://www.usa.gov/';
  sbir_base_create_menu_link($menu_name, $title, 10, $path, $plid, 1);

  $title = 'NIH ... Turning Discovery Into Health';
  $path = 'http://nih.gov/about/discovery';
  sbir_base_create_menu_link($menu_name, $title, 11, $path, $plid, 1);
}

/*
function sbir_global_template_order_panel_variants() {
  
  $variants = array(
    ''
  );
  db_update('page_manager_weights')
      ->fields(array(
        'weight' => $weight,
      ))
      ->condition('name', 'node_view__panel_context_365430e3-e888-4cca-9f5b-ef52e62462b2')
      ->execute();
}
 */