<?php

/**
 * Configure the WYSIWYG CkEditor for the Filtered HTML text format.
 * @param type $format The text format being updated
 * @param type $editor The name of the HTML WYSIWYG editor
 * @param type $settings Defines what buttons should appear on the WYSIWYG editor
 */
function sbir_wysiwyg_configure_ckeditor($format, $editor, $settings) {
  db_insert('wysiwyg')
      ->fields(array(
        'format' => $format,
        'editor' => $editor,
        'settings' => $settings,
      ))
      ->execute();
}

/**
 * Method that updates allowed HTML tags for a given text format
 * @param type $format The text format being updated
 * @param type $name The name of the format being updated
 * @param type $settings The tags that a content editor is allowed to input
 */
function sbir_wysiwyg_set_allowed_tags($format, $name, $settings) {

  db_update('filter')
      ->fields(array(
        'settings' => $settings,
      ))
      ->condition('format', $format)
      ->condition('name', $name)
      ->execute();
}

function sbir_wysiwyg_configure_imce() {
  $imce_settings[0] = array(
    'name' => 'User-1',
    'usertab' => 1,
    'filesize' => 0,
    'quota' => 0,
    'tuquota' => 0,
    'extensions' => '*',
    'dimensions' => '1200x1200',
    'filenum' => 0,
    'directories' => array(
      0 => array(
        'name' => '.',
        'subnav' => 1,
        'browse' => 1,
        'upload' => 1,
        'thumb' => 1,
        'delete' => 1,
        'resize' => 1,
      ),
    ),
    'thumbnails' => array(
      0 => array(
        'name' => 'Small',
        'dimensions' => '90x90',
        'prefix' => 'small_',
        'suffix' => '',
      ),
      1 => array(
        'name' => 'Medium',
        'dimensions' => '120x120',
        'prefix' => 'medium_',
        'suffix' => '',
      ),
      2 => array(
        'name' => 'Large',
        'dimensions' => '180x180',
        'prefix' => 'large_',
        'suffix' => '',
      ),
    ),
  );
  $imce_settings[1] = array(
    'name' => 'Sample profile',
    'usertab' => 1,
    'filesize' => 1,
    'quota' => 2,
    'tuquota' => 0,
    'extensions' => 'gif png jpg jpeg',
    'dimensions' => '800x600',
    'filenum' => 1,
    'directories' => array(
      0 => array(
        'name' => 'u%uid',
        'subnav' => 0,
        'browse' => 1,
        'upload' => 1,
        'thumb' => 1,
        'delete' => 0,
        'resize' => 0,
      ),
    ),
    'thumbnails' => array(
      0 => array(
        'name' => 'Thumb',
        'dimensions' => '90x90',
        'prefix' => 'thumb_',
        'suffix' => '',
      ),
    ),
  );
  variable_set('imce_profiles', $imce_settings);

  $imce_settings = array(
    4 => array(
      'weight' => 0,
      'public_pid' => 0,
      'private_pid' => 0,
    ),
    3 => array(
      'weight' => 0,
      'public_pid' => 0,
      'private_pid' => 0,
    ),
    6 => array(
      'weight' => 0,
      'public_pid' => 0,
      'private_pid' => 0,
    ),
    5 => array(
      'weight' => 0,
      'public_pid' => 0,
      'private_pid' => 0,
    ),
    8 => array(
      'weight' => 0,
      'public_pid' => 0,
      'private_pid' => 0,
    ),
    7 => array(
      'weight' => 0,
      'public_pid' => 0,
      'private_pid' => 0,
    ),
    2 => array(
      'weight' => 11,
      'public_pid' => 1,
      'private_pid' => 0,
    ),
    1 => array(
      'weight' => 12,
      'public_pid' => 0,
      'private_pid' => 0,
    ),
  );
  variable_set('imce_roles_profiles', $imce_settings);

  $imce_settings = 0;
  variable_set('imce_settings_absurls', $imce_settings);

  $imce_settings = 1;
  variable_set('imce_settings_disable_private', $imce_settings);

  $imce_settings = 0;
  variable_set('imce_settings_replace', $imce_settings);

  $imce_settings = '';
  variable_set('imce_settings_textarea', $imce_settings);

  $imce_settings = array(
    'object' => FALSE,
    'value' => 'scale_and_crop',
  );
  variable_set('imce_settings_thumb_method', $imce_settings);
}
