<?php

/**
 * Configure the WYSIWYG CkEditor for the Filtered HTML text format.
 * @param type $format The text format being updated
 * @param type $editor The name of the HTML WYSIWYG editor
 * @param type $settings Defines what buttons should appear on the WYSIWYG editor
 */
function sbir_wysiwyg_configure_ckeditor($format, $editor, $settings) {
  db_insert('wysiwyg')
      ->fields(array(
        'format' => $format,
        'editor' => $editor,        
        'settings' => $settings,
      ))
      ->execute();
}

/**
 * Method that updates allowed HTML tags for a given text format
 * @param type $format The text format being updated
 * @param type $name The name of the format being updated
 * @param type $settings The tags that a content editor is allowed to input
 */
function sbir_wysiwyg_set_allowed_tags($format, $name, $settings) {

  db_update('filter')
      ->fields(array(
        'settings' => $settings,
      ))
      ->condition('format', $format)
      ->condition('name', $name)
      ->execute();
}