<?php

function set_sbir_permissions() {

  // Create the role if necessary.
  $role = user_role_load_by_name('content author');
  if (!$role) {
    $role = new stdClass();
    $role->name = 'content author';
    user_role_save($role);
  }

  // Add the permissions to the role.
  $permissions = array(
    'administer menu',
    'access toolbar',
    'administer sbir',
    'create url aliases',
    'display site configuration menu',
    'display site configuration menu',
    'display site building menu',
    'create sbir_announcement content',
    'create sbir_basic_page content',
    'create sbir_block content',
    'create sbir_event content',
    'create sbir_file content',
    'create sbir_success_story content',
    'delete any sbir_announcement content',
    'delete any sbir_basic_page content',
    'delete any sbir_block content',
    'delete any sbir_event content',
    'delete any sbir_file content',
    'delete any sbir_success_story content',
    'edit any sbir_announcement content',
    'edit any sbir_basic_page content',
    'edit any sbir_block content',
    'edit any sbir_event content',
    'edit any sbir_file content',
    'edit any sbir_success_story content',
    'manipulate all queues',
    'moderate content from draft to needs_review',
    'moderate content from needs_review to draft',
    'moderate content from needs_review to published',
  );
  user_role_grant_permissions($role->rid, $permissions);

  // Create the role if necessary.
  $role = user_role_load_by_name('content editor');
  if (!$role) {
    $role = new stdClass();
    $role->name = 'content editor';
    user_role_save($role);
  }

  // Add the permissions to the role.
  $permissions = array(
    'administer menu',
    'access toolbar',
    'create url aliases',
    'create sbir_announcement content',
    'create sbir_basic_page content',
    'create sbir_block content',
    'create sbir_event content',
    'create sbir_file content',
    'create sbir_success_story content',
    'delete any sbir_announcement content',
    'delete any sbir_basic_page content',
    'delete any sbir_block content',
    'delete any sbir_event content',
    'delete any sbir_file content',
    'delete any sbir_success_story content',
    'edit any sbir_announcement content',
    'edit any sbir_basic_page content',
    'edit any sbir_block content',
    'edit any sbir_event content',
    'edit any sbir_file content',
    'edit any sbir_success_story content',
    'moderate content from draft to needs_review',
    'moderate content from needs_review to draft',
  );
  user_role_grant_permissions($role->rid, $permissions);

  // Create the role if necessary.
  $role = user_role_load_by_name('site moderator');
  if (!$role) {
    $role = new stdClass();
    $role->name = 'site moderator';
    user_role_save($role);
  }

  // Add the permissions to the role.
  $permissions = array(
    'administer menu',
    'access toolbar',
    'administer sbir',
    'create url aliases',
    'display site configuration menu',
    'display site building menu',
    'create sbir_announcement content',
    'create sbir_basic_page content',
    'create sbir_block content',
    'create sbir_event content',
    'create sbir_file content',
    'create sbir_success_story content',
    'delete any sbir_announcement content',
    'delete any sbir_basic_page content',
    'delete any sbir_block content',
    'delete any sbir_event content',
    'delete any sbir_file content',
    'delete any sbir_success_story content',
    'edit any sbir_announcement content',
    'edit any sbir_basic_page content',
    'edit any sbir_block content',
    'edit any sbir_event content',
    'edit any sbir_file content',
    'edit any sbir_success_story content',
    'manipulate all queues',
    'moderate content from draft to needs_review',
    'moderate content from needs_review to draft',
    'moderate content from needs_review to published',
  );
  user_role_grant_permissions($role->rid, $permissions);

  // Create the role if necessary.
  $role = user_role_load_by_name('advanced content editor');
  if (!$role) {
    $role = new stdClass();
    $role->name = 'advanced content editor';
    user_role_save($role);
  }

  // Add the permissions to the role.
  $permissions = array(
    'administer menu',
    'access toolbar',
    'administer sbir',
    'create url aliases',
    'display site configuration menu',
    'display site building menu',
    'create sbir_announcement content',
    'create sbir_basic_page content',
    'create sbir_block content',
    'create sbir_event content',
    'create sbir_file content',
    'create sbir_success_story content',
    'delete any sbir_announcement content',
    'delete any sbir_basic_page content',
    'delete any sbir_block content',
    'delete any sbir_event content',
    'delete any sbir_file content',
    'delete any sbir_success_story content',
    'edit any sbir_announcement content',
    'edit any sbir_basic_page content',
    'edit any sbir_block content',
    'edit any sbir_event content',
    'edit any sbir_file content',
    'edit any sbir_success_story content',
    'manipulate all queues',
    'moderate content from draft to needs_review',
    'moderate content from needs_review to draft',
    'moderate content from needs_review to published',
  );
  user_role_grant_permissions($role->rid, $permissions);

  // Create the role if necessary.
  $role = user_role_load_by_name('site manager');
  if (!$role) {
    $role = new stdClass();
    $role->name = 'site manager';
    user_role_save($role);
  }

  // Add the permissions to the role.
  $permissions = array(
    'administer menu',
    'access toolbar',
    'administer sbir',
    'create url aliases',
    'display site configuration menu',
    'display site building menu',
    'create sbir_announcement content',
    'create sbir_basic_page content',
    'create sbir_block content',
    'create sbir_event content',
    'create sbir_file content',
    'create sbir_success_story content',
    'delete any sbir_announcement content',
    'delete any sbir_basic_page content',
    'delete any sbir_block content',
    'delete any sbir_event content',
    'delete any sbir_file content',
    'delete any sbir_success_story content',
    'edit any sbir_announcement content',
    'edit any sbir_basic_page content',
    'edit any sbir_block content',
    'edit any sbir_event content',
    'edit any sbir_file content',
    'edit any sbir_success_story content',
    'manipulate all queues',
    'moderate content from draft to needs_review',
    'moderate content from needs_review to draft',
    'moderate content from needs_review to published',
  );
  user_role_grant_permissions($role->rid, $permissions);
}
