<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function sbir_block_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function sbir_block_node_info() {
  $items = array(
    'sbir_block' => array(
      'name' => t('Block'),
      'base' => 'node_content',
      'description' => t('This content type is to store text for custom block content.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}


function sbir_block_create_block($title, $alias = "", $node_type = 'sbir_block', $body_text = "", $footer_text = "") {

  $node = new stdClass();
  $node->title = $title;
  $node->type = $node_type;
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = 1;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 0;
  $node->sticky = 0;

  if (empty($body_text)) {
    $body_text = 'This is the ' . $title . ' block';
  }

  $node->body[$node->language][0]['value'] = $body_text;
  //$node->body[$node->language][0]['summary'] = text_summary($body_text);
  $node->body[$node->language][0]['format'] = 'filtered_html';

  if (!empty($footer_text)) {
    $node->field_footer[$node->language][0]['value'] = $footer_text;
    //$node->field_footer[$node->language][0]['summmary'] = $footer_text;
    $node->field_footer[$node->language][0]['format'] = 'filtered_html';
  }

  if (!empty($alias)) {
    $node->path['alias'] = $alias;
  }

  node_save($node);

  return $node->nid;
}
