<?php

/*
 * Implements hook_install
 */

function sbir_block_install() {
}

/*
 * Implements hook_enable
 */

function sbir_block_enable() {

  variable_set('comment_sbir_block', '0');
  variable_set('node_submitted_sbir_block', '0');
  variable_set('node_preview_sbir_block', '1');

  module_load_include('inc', 'sbir_block', 'includes/sbir_block.field_instance');

  block_create_field_instances();
}
