<?php

/**
 * Implements hook_views_api().
 */
function sbir_home_page_views_api() {
  return array('api' => 3.0);
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function sbir_home_page_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

function sbir_home_page_create_nodequeue() {

  $queue = array(
    'name' => 'home_page_blocks',
    'title' => 'Home Page Blocks',
    'subqueue_title' => '',
    'size' => 0,
    'link' => '',
    'link_remove' => '',
    'owner' => 'nodequeue',
    'show_in_ui' => 1,
    'show_in_tab' => 1,
    'show_in_links' => 0,
    'reference' => 0,
    'reverse' => 0,
    'i18n' => 0,
    'subqueues' => 1,
    'types' => array(
      0 => 'sbir_block',
    ),
    'roles' => array(),
    'count' => 0,
    'add_subqueue' => array(
      1 => 'Home Page Blocks',
    )    
  );

  $object = sbir_base_convert_array_to_object($queue);

  $qid = nodequeue_save($object);
  
  return $qid;
}