<?php

/**
 * Implements hook_views_api().
 */
function sbir_announcements_views_api() {
  return array('api' => 3.0);
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function sbir_announcements_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

function sbir_announcements_save_queue() {
  $queue = array(
    'name' => 'announcement',
    'title' => 'Announcement',
    'subqueue_title' => '',
    'size' => 0,
    'link' => '',
    'link_remove' => '',
    'owner' => 'nodequeue',
    'show_in_ui' => 1,
    'show_in_tab' => 1,
    'show_in_links' => 0,
    'reference' => 0,
    'reverse' => 0,
    'i18n' => 0,
    'subqueues' => 1,
    'types' => array(
      0 => 'sbir_announcement',
    ),
    'roles' => array(),
    'count' => 0,
    'add_subqueue' => array(
      1 => 'Announcement',
    )
  );

  $object = new stdClass();
  foreach ($queue as $key => $value) {
    $object->$key = $value;
  }

  nodequeue_save($object);
}
