<?php

/*
 * Implements hook_enable
 */

function sbir_file_install() {
}

/*
 * Implements hook_enable
 */

function sbir_file_enable() {

  variable_set('comment_sbir_basic_page', '0');
  variable_set('node_submitted_sbir_basic_page', '0');
  variable_set('node_preview_sbir_basic_page', '1');

  module_load_include('inc', 'sbir_file', 'includes/sbir_file.field_instance');

  file_create_field_instances();
}
