<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function sbir_announcement_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function sbir_announcement_node_info() {
  $items = array(
    'sbir_announcement' => array(
      'name' => t('Announcement'),
      'base' => 'node_content',
      'description' => t('Timely news items that need to appear on the  home page.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
