<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function sbir_basic_pages_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

function sbir_basic_pages_create_basic_page($title, $alias = "", $body_text = "", $summary_text = "", $node_type = 'sbir_basic_page') {
    
      $node = new stdClass();
      $node->title = $title;
      $node->type = $node_type;
      node_object_prepare($node);
      $node->language = LANGUAGE_NONE;
      $node->uid = 1;
      $node->status = 1;
      $node->promote = 0;
      $node->comment = 0;
      $node->sticky = 0;
    
      if (!empty($body_text)) {
        $node->body[$node->language][0]['value'] = $body_text;
      }
      //$node->body[$node->language][0]['summary'] = text_summary($body_text);
    
      if (!empty($summary_text)) {
        $node->body[$node->language][0]['summary'] = $summary_text;
      }
    
      $node->body[$node->language][0]['format'] = 'full_html';
    
      if (!empty($alias)) {
        $node->path['alias'] = $alias;
      }
    
      node_save($node);
    
      return $node->nid;
    }
    