<?php

/*
 * Implements hook_permission
 */

function sbir_admin_permission() {
  $permissions = array(
    'administer sbir_admin' => array(
      'title' => t('Administer SBIR'),
      'restrict access' => TRUE,
    ),
  );
  return $permissions;
}

/*
 * Implements hook_menu
 */

function sbir_admin_menu() {
  $items['admin/sbir/admin'] = array(
    'title' => 'SBIR',
    'description' => 'Administer SBIR',
    'position' => 'right',
    'weight' => 0,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer sbir_admin'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system')
  );
  $items['admin/sbir/admin/settings'] = array(
    'title' => 'Settings',
    'description' => t('Configure SBIR'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sbir_admin_settings_form'),
    'access arguments' => array('administer sbir_admin'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function sbir_admin_settings_form($form_state) {

  $to_email = variable_get('sbir_admin_to_email', '');
  $from_email = variable_get('sbir_admin_from_email', '');
  $new_subject = variable_get('sbir_admin_new_subject', '');
  $change_subject = variable_get('sbir_admin_change_subject', '');

  /*
    // Content Settings
    $form['content'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    );
    $form['content']['upload'] = array(
    '#name' => 'files[' . implode('_', $form['#parents']) . ']',
    '#type' => 'file',
    '#title' => t('Home page banner'),
    '#required' => TRUE,
    //'#title_display' => 'invisible',
    '#size' => 22,
    '#theme_wrappers' => array(),
    //'#weight' => -10,
    '#description' => 'This banner appears on the home page.',
    );
   */
  // Email Subscription Settings
  $form['email'] = array(
    '#type' => 'fieldset',
    '#title' => t('Email Subscription'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['email']['from'] = array(
    '#type' => 'textfield',
    '#title' => t('From Address'),
    '#required' => TRUE,
    '#default_value' => $from_email,
    "#description" => "This is be used as the 'from' address for signup notifications"
  );
  $form['email']['to'] = array(
    '#type' => 'textfield',
    '#title' => t('To Address'),
    '#required' => TRUE,
    '#default_value' => $to_email,
    '#description' => 'Signup notifications are sent to this email address',
  );
  $form['email']['new_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('New Subscription Subject'),
    '#required' => TRUE,
    '#default_value' => $new_subject,
    '#description' => 'This subject is used for new signup subscriptions',
  );
  $form['email']['change_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Change Subscription Subject'),
    '#required' => TRUE,
    '#default_value' => $change_subject,
    '#description' => 'This subject is used for updated email subscriptions',
  );

  $form['#validate'][] = '_validate_email_settings_input';

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save',
  );
  return $form;
}

/*
 * Implements hook_form_submit
 */

function sbir_admin_settings_form_submit($form, &$form_state) {

  variable_set('sbir_admin_to_email', $form['email']['to']['#value']);
  variable_set('sbir_admin_from_email', $form['email']['from']['#value']);
  variable_set('sbir_admin_new_subject', $form['email']['change_subject']['#value']);
  variable_set('sbir_admin_change_subject', $form['email']['new_subject']['#value']);

  drupal_set_message('Email settings have been successfully saved.');
}

/*
 * Implements hook_form_alter
 */

function sbir_admin_form_alter(&$form, &$form_state, $form_id) {

  //make local copy of form_id
  $node_form_id = $form_id;

  // disable autocomple for user login and user profile forms
  if ($form_id == "user_login" ||
      $form_id == "user_profile_form") {
    $form['#attached']['js'] = array(drupal_get_path('module', 'sbir_admin') . '/js/sbir_admin.js');
  }
  //overwrite all different node type forms to "node_form"
  //so only nodes will have this checkbox
  $node_form_type = '';
  if (substr($node_form_id, -10) == '_node_form') {
    $node_form_type = 'node_form';
  }

  //Also this variant was proposed
  /*
    if( $form['#id'] == 'node-form' ){
    $test_form_id = 'node_form';
    }
   */

  switch ($node_form_type) {

    // Add a checkbox to all node edit forms that allows user to 
    // enable/disable the menu item
    case 'node_form':

      if ($form_id != 'sbir_subscription_node_form') {
        //dpm($form['menu']['link']);
        //get mlid, if mlid captured
        //this is node editing action
        $mlid = 0;

        if (isset($form['menu']['link'] ['mlid']['#value']) &&
            $form['menu']['link']['mlid']['#value'] > 0) {
          $mlid = $form['menu']['link']['mlid']['#value'];
          $menuItem = menu_link_load($mlid);
        }

        //add dummy hidden/enabled checkbox and
        //use previous value for checkbox status if available
        $form['menu']['link']['sbir_menu_item_enabled'] = array(
          '#type' => 'checkbox',
          '#title' => t('Enabled'),
          '#default_value' => ($mlid == 0 ? 1 : ($menuItem['hidden'] ? 0 : 1)),
          '#description' =>
          t('Menu items that are not enabled will appear in any menus.'),
        );
      }

      //hide the banner upload field (we don't want content editors to upload new ones)
      $form['field_banner']['#attributes']['style'] = 'display:none';
      $form ['#attached']['css'] = array(drupal_get_path('module', 'sbir_admin') . '/css/sbir_admin.css');
      $form['#attached']['js'] = array(drupal_get_path('module', 'sbir_admin') . '/js/sbir_admin.js');

      //$form['menu']['link']['description']['#attributes']['style'] = 'display:none';
      if ($form['type'] ['#value'] == 'sbir_block' ||
          $form ['type']['#value'] == 'sbir_file' ||
          $form['type']['#value'] == 'sbir_subscription') {
        unset($form['menu']);
        unset($form['options']['promote']);
        unset($form['options']['sticky']);
        unset($form['body']['#attributes']['class'][0]);
        unset($form['path'])

        ;
      }
      break;
  }
}

/*
 * Implements hook_node_presave
 */

function sbir_admin_node_presave($node) {
  if (isset($node->menu['sbir_menu_item_enabled'])) {
    $node->menu['hidden'] = $node->menu['sbir_menu_item_enabled'] == 1 ? 0 : 1;
  }
}

// Validate form input for SBIR Email Signup
function _validate_email_settings_input($form, &$form_state) {

  $from_email = check_plain($form_state['input']['from']);
  $to_email = check_plain($form_state['input']['to']);

  $new_subject = check_plain($form_state['input']['new_subject']);
  $change_subject = check_plain($form_state['input']['change_subject']);

  if (!filter_var($from_email, FILTER_VALIDATE_EMAIL)) {
    form_set_error('Email Validation', "From Address is not in the corrent format: jdoe@example.com");
  }

  if (!filter_var($to_email, FILTER_VALIDATE_EMAIL)) {
    form_set_error('Email Validation', "To Address is not in the corrent format: jdoe@example.com");
  }
}
